# Generated by Django 2.1.4 on 2022-11-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('realName', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
            ],
        ),
    ]
