# Generated by Django 3.2.16 on 2022-12-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('videos', models.CharField(max_length=1000)),
                ('images', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=1000)),
                ('create_time', models.DateTimeField()),
                ('userImage', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=100)),
                ('book_spu_number', models.CharField(max_length=50)),
                ('book_price', models.FloatField()),
                ('book_tips', models.CharField(max_length=200)),
                ('book_outlet', models.CharField(max_length=100)),
                ('comments_id', models.ManyToManyField(to='spider.Comment')),
            ],
        ),
    ]
